// Demo roster: real public figures with factual career data drawn from
// general knowledge. Booking fees, ratings, availability and reviews are
// FICTIONAL demo values. All imagery in the app is generated placeholder
// art — no endorsement or affiliation is implied. See README "Demo data".

export interface SeedCelebrity {
  slug: string;
  name: string;
  tagline: string;
  bio: string;
  gender: "female" | "male" | "nonbinary";
  category: string; // category slug
  country: string; // ISO code
  manager: number; // 1-based index into MANAGERS
  featured?: boolean;
  trendingScore: number;
  popularity: number;
  rating: number;
  reviewCount: number;
  followers: number;
  feeFrom: number; // USD (not cents)
  feeTo: number;
  availability: "available" | "limited" | "booked";
  yearsActive: number;
  accentHue: number;
  achievements: string[];
  awards: { name: string; year: number; work?: string }[];
  works: { title: string; year: number; kind: "film" | "album" | "book" | "show" | "event"; meta?: string }[];
  socials: { platform: string; handle: string; followers: number }[];
  faq: { q: string; a: string }[];
}

export const CATEGORIES = [
  { slug: "music", name: "Music", tagline: "Headliners, hitmakers and living legends" },
  { slug: "film", name: "Film & Television", tagline: "Screen icons and award-season names" },
  { slug: "sports", name: "Sports", tagline: "Champions, record-holders and game-changers" },
  { slug: "comedy", name: "Comedy", tagline: "Stand-up stars and late-night favorites" },
  { slug: "speakers", name: "Keynote Speakers", tagline: "Minds that move rooms" },
  { slug: "influencers", name: "Creators & Influencers", tagline: "The internet's biggest audiences" },
  { slug: "tv-hosts", name: "TV Hosts", tagline: "Broadcast royalty and beloved presenters" },
  { slug: "authors", name: "Authors", tagline: "Bestselling writers and thought leaders" },
  { slug: "public-figures", name: "Public Figures", tagline: "Statesmen, advocates and cultural voices" },
  { slug: "fashion", name: "Fashion & Modeling", tagline: "Runway legends and style icons" },
] as const;

export const COUNTRIES = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
] as const;

export const MANAGERS = [
  { name: "Victoria Ashford", agency: "Ashford & Gray Talent", title: "Founding Partner", years: 22 },
  { name: "Marcus Chen", agency: "Meridian Artists Group", title: "Head of Talent", years: 18 },
  { name: "Amara Okafor", agency: "Continental Entertainment", title: "Managing Director", years: 15 },
  { name: "James Whitlock", agency: "Whitlock Sports & Media", title: "President", years: 25 },
  { name: "Sofia Reyes", agency: "Luminary Speakers Bureau", title: "SVP, Global Bookings", years: 14 },
  { name: "David Kim", agency: "Northlight Creator Partners", title: "Chief Talent Officer", years: 11 },
] as const;

export const CELEBRITIES: SeedCelebrity[] = [
  // ───────── Music ─────────
  {
    slug: "taylor-swift",
    name: "Taylor Swift",
    tagline: "The most-awarded artist in Grammy Album of the Year history",
    bio: "Taylor Swift is a singer-songwriter whose genre-spanning catalogue and record-shattering Eras Tour made her one of the defining cultural forces of her generation. She is the only artist to win the Grammy for Album of the Year four times, and her re-recorded albums rewrote the rules of music ownership.",
    gender: "female",
    category: "music",
    country: "US",
    manager: 1,
    featured: true,
    trendingScore: 98,
    popularity: 100,
    rating: 4.9,
    reviewCount: 187,
    followers: 511_000_000,
    feeFrom: 1_500_000,
    feeTo: 5_000_000,
    availability: "limited",
    yearsActive: 20,
    accentHue: 305,
    achievements: [
      "First artist to win Grammy Album of the Year four times",
      "The Eras Tour became the first tour to gross over $1 billion",
      "14 Billboard 200 No. 1 albums",
      "Time Person of the Year 2023",
    ],
    awards: [
      { name: "Grammy Award — Album of the Year", year: 2024, work: "Midnights" },
      { name: "Grammy Award — Album of the Year", year: 2021, work: "Folklore" },
      { name: "Grammy Award — Album of the Year", year: 2016, work: "1989" },
      { name: "Grammy Award — Album of the Year", year: 2010, work: "Fearless" },
    ],
    works: [
      { title: "The Tortured Poets Department", year: 2024, kind: "album" },
      { title: "Midnights", year: 2022, kind: "album" },
      { title: "Folklore", year: 2020, kind: "album" },
      { title: "1989", year: 2014, kind: "album" },
      { title: "The Eras Tour", year: 2023, kind: "event", meta: "149-date stadium tour" },
    ],
    socials: [
      { platform: "Instagram", handle: "@taylorswift", followers: 283_000_000 },
      { platform: "TikTok", handle: "@taylorswift", followers: 28_000_000 },
      { platform: "X", handle: "@taylorswift13", followers: 95_000_000 },
    ],
    faq: [
      { q: "What events is Taylor typically available for?", a: "Select private performances, brand partnerships and charity galas, subject to tour schedule. Full concerts require 9–12 months lead time." },
      { q: "What is included in a private performance?", a: "A tailored set (typically 45–90 minutes), full band and production advance with the venue's technical team." },
    ],
  },
  {
    slug: "beyonce",
    name: "Beyoncé",
    tagline: "The most-awarded artist in Grammy history",
    bio: "Beyoncé Knowles-Carter is a singer, songwriter and businesswoman whose career — from Destiny's Child to Renaissance and Cowboy Carter — has redefined the modern superstar. With 32 Grammy wins she holds the record for the most in history, and her visual albums changed how the industry releases music.",
    gender: "female",
    category: "music",
    country: "US",
    manager: 1,
    featured: true,
    trendingScore: 93,
    popularity: 99,
    rating: 4.9,
    reviewCount: 142,
    followers: 340_000_000,
    feeFrom: 1_000_000,
    feeTo: 4_000_000,
    availability: "limited",
    yearsActive: 27,
    accentHue: 45,
    achievements: [
      "Most Grammy Awards won by any artist (32)",
      "First Black woman to top the Billboard country albums chart",
      "Renaissance World Tour grossed over $579 million",
      "First female artist with eight consecutive No. 1 debut albums",
    ],
    awards: [
      { name: "Grammy Award — Best Country Album", year: 2025, work: "Cowboy Carter" },
      { name: "Grammy Award — Best Dance/Electronic Album", year: 2023, work: "Renaissance" },
      { name: "Grammy Award — Song of the Year", year: 2010, work: "Single Ladies" },
    ],
    works: [
      { title: "Cowboy Carter", year: 2024, kind: "album" },
      { title: "Renaissance", year: 2022, kind: "album" },
      { title: "Lemonade", year: 2016, kind: "album" },
      { title: "Homecoming", year: 2019, kind: "film", meta: "Netflix concert documentary" },
    ],
    socials: [
      { platform: "Instagram", handle: "@beyonce", followers: 310_000_000 },
      { platform: "X", handle: "@Beyonce", followers: 15_000_000 },
    ],
    faq: [
      { q: "Does Beyoncé perform at private events?", a: "Very selectively. Private performances are considered for milestone occasions and heritage brands with 12+ months lead time." },
    ],
  },
  {
    slug: "the-weeknd",
    name: "The Weeknd",
    tagline: "The first artist to reach 100 million monthly Spotify listeners",
    bio: "Abel Tesfaye, known as The Weeknd, is a Canadian singer and producer whose moody R&B and stadium-scale pop made him one of the most-streamed artists on the planet. His Super Bowl LV halftime show and the record-breaking single Blinding Lights cemented his place in pop history.",
    gender: "male",
    category: "music",
    country: "CA",
    manager: 1,
    featured: true,
    trendingScore: 88,
    popularity: 94,
    rating: 4.8,
    reviewCount: 96,
    followers: 180_000_000,
    feeFrom: 750_000,
    feeTo: 2_500_000,
    availability: "available",
    yearsActive: 15,
    accentHue: 15,
    achievements: [
      "Blinding Lights: the most-streamed song in Spotify history at its peak",
      "First artist to hit 100M monthly Spotify listeners",
      "Headlined the Super Bowl LV Halftime Show",
    ],
    awards: [
      { name: "Grammy Award — Best Urban Contemporary Album", year: 2018, work: "Starboy" },
      { name: "Grammy Award — Best R&B Performance", year: 2016, work: "Earned It" },
    ],
    works: [
      { title: "Hurry Up Tomorrow", year: 2025, kind: "album" },
      { title: "Dawn FM", year: 2022, kind: "album" },
      { title: "After Hours", year: 2020, kind: "album" },
      { title: "Starboy", year: 2016, kind: "album" },
    ],
    socials: [
      { platform: "Instagram", handle: "@theweeknd", followers: 76_000_000 },
      { platform: "X", handle: "@theweeknd", followers: 17_000_000 },
    ],
    faq: [
      { q: "What lead time is required for festival bookings?", a: "Headline festival slots are typically confirmed 6–10 months out." },
    ],
  },
  {
    slug: "burna-boy",
    name: "Burna Boy",
    tagline: "The African Giant — first Nigerian artist to headline a US stadium",
    bio: "Burna Boy is a Nigerian singer-songwriter whose Afro-fusion sound carried African music to the world's biggest stages. A Grammy winner and the first Nigerian artist to sell out a US stadium, he stands at the center of the global Afrobeats movement.",
    gender: "male",
    category: "music",
    country: "NG",
    manager: 3,
    featured: true,
    trendingScore: 91,
    popularity: 88,
    rating: 4.8,
    reviewCount: 74,
    followers: 32_000_000,
    feeFrom: 350_000,
    feeTo: 1_200_000,
    availability: "available",
    yearsActive: 13,
    accentHue: 150,
    achievements: [
      "First Nigerian artist to headline and sell out a US stadium (Citi Field)",
      "Grammy winner — Best Global Music Album",
      "First African artist to headline a UK stadium (London Stadium)",
    ],
    awards: [
      { name: "Grammy Award — Best Global Music Album", year: 2021, work: "Twice as Tall" },
      { name: "BET Award — Best International Act", year: 2021 },
    ],
    works: [
      { title: "I Told Them...", year: 2023, kind: "album" },
      { title: "Love, Damini", year: 2022, kind: "album" },
      { title: "African Giant", year: 2019, kind: "album" },
    ],
    socials: [
      { platform: "Instagram", handle: "@burnaboygram", followers: 18_000_000 },
      { platform: "X", handle: "@burnaboy", followers: 5_000_000 },
    ],
    faq: [
      { q: "Is Burna Boy available for weddings?", a: "Yes — private performances for weddings and milestone events are among his most requested bookings." },
    ],
  },
  {
    slug: "adele",
    name: "Adele",
    tagline: "The voice of a generation — 16 Grammys, one residency, no equal",
    bio: "Adele Adkins is a British singer-songwriter whose ballads have soundtracked two decades of heartbreak and healing. Her albums 21 and 25 are among the best-selling of the century, and her Las Vegas residency became one of the most sought-after tickets in live music.",
    gender: "female",
    category: "music",
    country: "GB",
    manager: 1,
    trendingScore: 72,
    popularity: 92,
    rating: 4.9,
    reviewCount: 68,
    followers: 90_000_000,
    feeFrom: 1_000_000,
    feeTo: 3_500_000,
    availability: "booked",
    yearsActive: 19,
    accentHue: 230,
    achievements: [
      "16 Grammy Awards including two Album of the Year wins",
      "21 spent 24 weeks at No. 1 on the Billboard 200",
      "Academy Award winner for Skyfall",
    ],
    awards: [
      { name: "Grammy Award — Album of the Year", year: 2017, work: "25" },
      { name: "Grammy Award — Album of the Year", year: 2012, work: "21" },
      { name: "Academy Award — Best Original Song", year: 2013, work: "Skyfall" },
    ],
    works: [
      { title: "30", year: 2021, kind: "album" },
      { title: "25", year: 2015, kind: "album" },
      { title: "21", year: 2011, kind: "album" },
      { title: "Weekends with Adele", year: 2022, kind: "event", meta: "Las Vegas residency" },
    ],
    socials: [
      { platform: "Instagram", handle: "@adele", followers: 57_000_000 },
    ],
    faq: [
      { q: "When will Adele next be available?", a: "Adele is currently on hiatus from live performance. Join the waitlist to be notified when her calendar reopens." },
    ],
  },

  // ───────── Film & Television ─────────
  {
    slug: "denzel-washington",
    name: "Denzel Washington",
    tagline: "Two Oscars, a Tony, and five decades of command performances",
    bio: "Denzel Washington is an actor, director and producer widely regarded as one of the greatest performers of his era. From Malcolm X and Training Day to Fences and Gladiator II, his body of work spans two Academy Awards, a Tony Award and the Presidential Medal of Freedom.",
    gender: "male",
    category: "film",
    country: "US",
    manager: 2,
    featured: true,
    trendingScore: 76,
    popularity: 91,
    rating: 4.9,
    reviewCount: 58,
    followers: 12_000_000,
    feeFrom: 500_000,
    feeTo: 1_500_000,
    availability: "limited",
    yearsActive: 45,
    accentHue: 40,
    achievements: [
      "Two Academy Awards (Glory, Training Day)",
      "Tony Award for Fences on Broadway",
      "Presidential Medal of Freedom recipient (2022)",
      "10 Academy Award nominations",
    ],
    awards: [
      { name: "Academy Award — Best Actor", year: 2002, work: "Training Day" },
      { name: "Academy Award — Best Supporting Actor", year: 1990, work: "Glory" },
      { name: "Tony Award — Best Actor in a Play", year: 2010, work: "Fences" },
    ],
    works: [
      { title: "Gladiator II", year: 2024, kind: "film" },
      { title: "The Equalizer 3", year: 2023, kind: "film" },
      { title: "Fences", year: 2016, kind: "film", meta: "Director & lead" },
      { title: "Malcolm X", year: 1992, kind: "film" },
    ],
    socials: [
      { platform: "Instagram", handle: "@denzelwashingtonofficlal", followers: 4_000_000 },
    ],
    faq: [
      { q: "Does Mr. Washington accept speaking engagements?", a: "Yes — commencements, leadership summits and film industry events are considered on a limited basis each year." },
    ],
  },
  {
    slug: "zendaya",
    name: "Zendaya",
    tagline: "Two-time Emmy winner and the face of a new Hollywood",
    bio: "Zendaya is an actress and producer who became the youngest two-time Emmy winner for lead actress in a drama for Euphoria, and anchors two of the biggest franchises in film — Dune and Spider-Man. She is also one of fashion's most influential red-carpet forces.",
    gender: "female",
    category: "film",
    country: "US",
    manager: 2,
    featured: true,
    trendingScore: 94,
    popularity: 95,
    rating: 4.8,
    reviewCount: 81,
    followers: 220_000_000,
    feeFrom: 400_000,
    feeTo: 1_200_000,
    availability: "available",
    yearsActive: 15,
    accentHue: 285,
    achievements: [
      "Youngest two-time Emmy winner for Outstanding Lead Actress in a Drama",
      "Golden Globe winner for Euphoria",
      "CFDA Fashion Icon Award (2021), its youngest-ever recipient",
    ],
    awards: [
      { name: "Emmy — Outstanding Lead Actress in a Drama", year: 2022, work: "Euphoria" },
      { name: "Emmy — Outstanding Lead Actress in a Drama", year: 2020, work: "Euphoria" },
      { name: "Golden Globe — Best Actress in a Drama Series", year: 2023, work: "Euphoria" },
    ],
    works: [
      { title: "Dune: Part Two", year: 2024, kind: "film" },
      { title: "Challengers", year: 2024, kind: "film" },
      { title: "Euphoria", year: 2019, kind: "show", meta: "HBO" },
      { title: "Spider-Man: No Way Home", year: 2021, kind: "film" },
    ],
    socials: [
      { platform: "Instagram", handle: "@zendaya", followers: 180_000_000 },
      { platform: "X", handle: "@Zendaya", followers: 22_000_000 },
    ],
    faq: [
      { q: "Is Zendaya available for brand campaigns?", a: "Luxury fashion, beauty and tech partnerships are reviewed by her team quarterly." },
    ],
  },
  {
    slug: "ryan-reynolds",
    name: "Ryan Reynolds",
    tagline: "Deadpool himself — actor, founder, and marketing phenomenon",
    bio: "Ryan Reynolds is a Canadian actor and entrepreneur whose Deadpool franchise redefined the comic-book comedy. Off screen, his ventures — Aviation Gin, Mint Mobile and Wrexham AFC — made him one of the most bankable founder-celebrities in the world.",
    gender: "male",
    category: "film",
    country: "CA",
    manager: 2,
    trendingScore: 85,
    popularity: 90,
    rating: 4.8,
    reviewCount: 63,
    followers: 105_000_000,
    feeFrom: 300_000,
    feeTo: 1_000_000,
    availability: "available",
    yearsActive: 30,
    accentHue: 0,
    achievements: [
      "Deadpool & Wolverine: highest-grossing R-rated film ever",
      "Sold Mint Mobile to T-Mobile in a $1.35B deal",
      "Co-owner of Wrexham AFC, subject of Welcome to Wrexham",
    ],
    awards: [
      { name: "People's Choice Award — Male Movie Star", year: 2017 },
      { name: "Emmy nomination — Welcome to Wrexham", year: 2023 },
    ],
    works: [
      { title: "Deadpool & Wolverine", year: 2024, kind: "film" },
      { title: "Free Guy", year: 2021, kind: "film" },
      { title: "Welcome to Wrexham", year: 2022, kind: "show", meta: "FX docuseries" },
    ],
    socials: [
      { platform: "Instagram", handle: "@vancityreynolds", followers: 52_000_000 },
      { platform: "X", handle: "@VancityReynolds", followers: 22_000_000 },
    ],
    faq: [
      { q: "Does Ryan do corporate keynotes?", a: "Yes — marketing and entrepreneurship keynotes are a signature offering, often paired with brand collaborations." },
    ],
  },
  {
    slug: "lupita-nyongo",
    name: "Lupita Nyong'o",
    tagline: "Oscar winner and global ambassador for African storytelling",
    bio: "Lupita Nyong'o is a Kenyan-Mexican actress who won the Academy Award for her debut feature performance in 12 Years a Slave. From Black Panther to Us and A Quiet Place: Day One, she pairs blockbuster reach with fearless dramatic range.",
    gender: "female",
    category: "film",
    country: "US",
    manager: 2,
    trendingScore: 70,
    popularity: 84,
    rating: 4.9,
    reviewCount: 41,
    followers: 15_000_000,
    feeFrom: 250_000,
    feeTo: 750_000,
    availability: "available",
    yearsActive: 13,
    accentHue: 200,
    achievements: [
      "Academy Award for her first feature film role",
      "Star of Black Panther, the first superhero film nominated for Best Picture",
      "New York Times bestselling children's author (Sulwe)",
    ],
    awards: [
      { name: "Academy Award — Best Supporting Actress", year: 2014, work: "12 Years a Slave" },
      { name: "NAACP Image Award — Outstanding Actress", year: 2020, work: "Us" },
    ],
    works: [
      { title: "A Quiet Place: Day One", year: 2024, kind: "film" },
      { title: "Black Panther: Wakanda Forever", year: 2022, kind: "film" },
      { title: "Us", year: 2019, kind: "film" },
      { title: "Sulwe", year: 2019, kind: "book" },
    ],
    socials: [
      { platform: "Instagram", handle: "@lupitanyongo", followers: 10_000_000 },
    ],
    faq: [
      { q: "What causes does Lupita champion?", a: "She frequently partners with organizations supporting girls' education and African cinema — charity galas are warmly considered." },
    ],
  },

  // ───────── Sports ─────────
  {
    slug: "serena-williams",
    name: "Serena Williams",
    tagline: "23 Grand Slams — the greatest to ever swing a racket",
    bio: "Serena Williams is a 23-time Grand Slam singles champion whose dominance across three decades made her one of the most consequential athletes in history. Since evolving beyond the court she has become a venture investor, founder and sought-after voice on excellence and reinvention.",
    gender: "female",
    category: "sports",
    country: "US",
    manager: 4,
    featured: true,
    trendingScore: 78,
    popularity: 93,
    rating: 4.9,
    reviewCount: 66,
    followers: 30_000_000,
    feeFrom: 350_000,
    feeTo: 900_000,
    availability: "available",
    yearsActive: 27,
    accentHue: 330,
    achievements: [
      "23 Grand Slam singles titles — the most of the Open Era",
      "Four Olympic gold medals",
      "319 weeks ranked world No. 1",
      "Founder of Serena Ventures",
    ],
    awards: [
      { name: "AP Female Athlete of the Decade", year: 2019 },
      { name: "Laureus Sportswoman of the Year", year: 2016 },
    ],
    works: [
      { title: "US Open Champion", year: 2014, kind: "event", meta: "18th Grand Slam" },
      { title: "Australian Open Champion", year: 2017, kind: "event", meta: "23rd Grand Slam, won while pregnant" },
      { title: "King Richard", year: 2021, kind: "film", meta: "Executive producer" },
    ],
    socials: [
      { platform: "Instagram", handle: "@serenawilliams", followers: 18_000_000 },
      { platform: "X", handle: "@serenawilliams", followers: 10_000_000 },
    ],
    faq: [
      { q: "What are Serena's most popular bookings?", a: "Leadership keynotes, women-in-business summits and brand ambassadorships." },
    ],
  },
  {
    slug: "lionel-messi",
    name: "Lionel Messi",
    tagline: "Eight Ballons d'Or and the World Cup — football's final answer",
    bio: "Lionel Messi is an Argentine forward considered by many the greatest footballer of all time. Captaining Argentina to the 2022 World Cup completed a career of eight Ballon d'Or wins, and his move to Inter Miami reshaped football in North America.",
    gender: "male",
    category: "sports",
    country: "AR",
    manager: 4,
    featured: true,
    trendingScore: 90,
    popularity: 98,
    rating: 4.9,
    reviewCount: 92,
    followers: 500_000_000,
    feeFrom: 800_000,
    feeTo: 2_500_000,
    availability: "limited",
    yearsActive: 21,
    accentHue: 210,
    achievements: [
      "2022 FIFA World Cup champion and Golden Ball winner",
      "Record eight Ballon d'Or awards",
      "All-time top scorer for Barcelona and Argentina",
      "Most followed Instagram account of any athlete",
    ],
    awards: [
      { name: "Ballon d'Or", year: 2023 },
      { name: "FIFA World Cup — Golden Ball", year: 2022 },
      { name: "Laureus World Sportsman of the Year", year: 2023 },
    ],
    works: [
      { title: "FIFA World Cup Victory", year: 2022, kind: "event", meta: "Qatar" },
      { title: "Copa América Champion", year: 2024, kind: "event" },
      { title: "Inter Miami CF", year: 2023, kind: "event", meta: "MLS signing" },
    ],
    socials: [
      { platform: "Instagram", handle: "@leomessi", followers: 505_000_000 },
    ],
    faq: [
      { q: "Is Messi available during the season?", a: "Appearances are scheduled around the MLS calendar; off-season windows book 6+ months ahead." },
    ],
  },
  {
    slug: "usain-bolt",
    name: "Usain Bolt",
    tagline: "The fastest human in recorded history",
    bio: "Usain Bolt is a Jamaican sprinter who holds the world records in the 100m and 200m — marks untouched since 2009. An eight-time Olympic gold medalist, his charisma made him athletics' greatest showman and a beloved global ambassador for sport.",
    gender: "male",
    category: "sports",
    country: "JM",
    manager: 4,
    trendingScore: 65,
    popularity: 85,
    rating: 4.8,
    reviewCount: 49,
    followers: 25_000_000,
    feeFrom: 150_000,
    feeTo: 500_000,
    availability: "available",
    yearsActive: 18,
    accentHue: 130,
    achievements: [
      "World records: 100m (9.58s) and 200m (19.19s)",
      "Eight Olympic gold medals",
      "Only sprinter to win 100m and 200m at three consecutive Olympics",
    ],
    awards: [
      { name: "IAAF World Athlete of the Year", year: 2016 },
      { name: "Laureus World Sportsman of the Year", year: 2017 },
    ],
    works: [
      { title: "Berlin World Championships", year: 2009, kind: "event", meta: "9.58s world record" },
      { title: "Rio Olympics — Triple Triple", year: 2016, kind: "event" },
      { title: "I Am Bolt", year: 2016, kind: "film", meta: "Documentary" },
    ],
    socials: [
      { platform: "Instagram", handle: "@usainbolt", followers: 13_000_000 },
      { platform: "X", handle: "@usainbolt", followers: 8_000_000 },
    ],
    faq: [
      { q: "What does a Bolt appearance include?", a: "Meet-and-greets, motivational talks and race-day activations; he is famously generous with fan time." },
    ],
  },
  {
    slug: "lewis-hamilton",
    name: "Lewis Hamilton",
    tagline: "Seven F1 world titles and a record 100+ wins",
    bio: "Sir Lewis Hamilton is a British Formula 1 driver whose seven world championships tie the all-time record and whose 100+ race wins stand alone in history. Now driving for Ferrari, he is also motorsport's most prominent advocate for diversity and sustainability.",
    gender: "male",
    category: "sports",
    country: "GB",
    manager: 4,
    trendingScore: 83,
    popularity: 89,
    rating: 4.8,
    reviewCount: 47,
    followers: 40_000_000,
    feeFrom: 400_000,
    feeTo: 1_000_000,
    availability: "limited",
    yearsActive: 18,
    accentHue: 350,
    achievements: [
      "Seven Formula 1 World Championships",
      "Most race wins (105) and pole positions in F1 history",
      "Knighted for services to motorsport (2021)",
      "Founder of Mission 44 foundation",
    ],
    awards: [
      { name: "F1 World Champion", year: 2020 },
      { name: "BBC Sports Personality of the Year", year: 2014 },
      { name: "Laureus World Sportsman of the Year", year: 2020 },
    ],
    works: [
      { title: "Ferrari debut season", year: 2025, kind: "event" },
      { title: "Seventh World Championship", year: 2020, kind: "event", meta: "Equalled Schumacher's record" },
    ],
    socials: [
      { platform: "Instagram", handle: "@lewishamilton", followers: 38_000_000 },
    ],
    faq: [
      { q: "When is Lewis available?", a: "Appearances follow the F1 calendar — winter break and select race-weekend activations." },
    ],
  },

  // ───────── Comedy ─────────
  {
    slug: "kevin-hart",
    name: "Kevin Hart",
    tagline: "Comedy's biggest box office — on stage and on screen",
    bio: "Kevin Hart is a comedian, actor and entrepreneur whose arena tours rank among the highest-grossing in stand-up history. Between blockbuster franchises like Jumanji, his media company Hartbeat, and a relentless touring schedule, he is one of the hardest-working names in entertainment.",
    gender: "male",
    category: "comedy",
    country: "US",
    manager: 4,
    featured: true,
    trendingScore: 86,
    popularity: 92,
    rating: 4.8,
    reviewCount: 103,
    followers: 180_000_000,
    feeFrom: 300_000,
    feeTo: 1_000_000,
    availability: "available",
    yearsActive: 24,
    accentHue: 25,
    achievements: [
      "First comedian to sell out an NFL stadium (What Now?, 2015)",
      "Mark Twain Prize for American Humor (2024)",
      "Founder of Hartbeat, valued at $650M",
    ],
    awards: [
      { name: "Mark Twain Prize for American Humor", year: 2024 },
      { name: "People's Choice — Favorite Comedic Movie Actor", year: 2015 },
    ],
    works: [
      { title: "Reality Check Tour", year: 2023, kind: "event" },
      { title: "Jumanji: Welcome to the Jungle", year: 2017, kind: "film" },
      { title: "Irresponsible", year: 2019, kind: "show", meta: "Netflix special" },
    ],
    socials: [
      { platform: "Instagram", handle: "@kevinhart4real", followers: 177_000_000 },
      { platform: "X", handle: "@KevinHart4real", followers: 36_000_000 },
    ],
    faq: [
      { q: "Does Kevin host corporate events?", a: "Yes — hosting, custom sets and fireside conversations for summits and award shows are core offerings." },
    ],
  },
  {
    slug: "ali-wong",
    name: "Ali Wong",
    tagline: "Emmy and Golden Globe winner who redefined the comedy special",
    bio: "Ali Wong is a comedian, actress and writer whose specials Baby Cobra and Hard Knock Wife — both filmed while pregnant — became instant classics. Her Emmy- and Golden Globe-winning turn in Beef confirmed her as one of the sharpest performers of her generation.",
    gender: "female",
    category: "comedy",
    country: "US",
    manager: 4,
    trendingScore: 74,
    popularity: 80,
    rating: 4.8,
    reviewCount: 38,
    followers: 4_000_000,
    feeFrom: 150_000,
    feeTo: 400_000,
    availability: "available",
    yearsActive: 18,
    accentHue: 320,
    achievements: [
      "Emmy and Golden Globe winner for Beef",
      "Three acclaimed Netflix specials",
      "New York Times bestselling author (Dear Girls)",
    ],
    awards: [
      { name: "Emmy — Outstanding Lead Actress in a Limited Series", year: 2023, work: "Beef" },
      { name: "Golden Globe — Best Actress in a Limited Series", year: 2024, work: "Beef" },
    ],
    works: [
      { title: "Beef", year: 2023, kind: "show", meta: "Netflix" },
      { title: "Baby Cobra", year: 2016, kind: "show", meta: "Netflix special" },
      { title: "Dear Girls", year: 2019, kind: "book" },
    ],
    socials: [
      { platform: "Instagram", handle: "@aliwong", followers: 2_000_000 },
    ],
    faq: [
      { q: "Does Ali perform at private events?", a: "Select private shows and college dates each season; her team reviews fit carefully." },
    ],
  },
  {
    slug: "trevor-noah",
    name: "Trevor Noah",
    tagline: "From Soweto to The Daily Show — comedy's global statesman",
    bio: "Trevor Noah is a South African comedian and author who hosted The Daily Show for seven years and wrote the era-defining memoir Born a Crime. A three-time Grammy Awards host, he moves fluently between stand-up arenas, moderated conversations and global stages.",
    gender: "male",
    category: "comedy",
    country: "ZA",
    manager: 4,
    featured: true,
    trendingScore: 80,
    popularity: 86,
    rating: 4.9,
    reviewCount: 55,
    followers: 45_000_000,
    feeFrom: 250_000,
    feeTo: 650_000,
    availability: "available",
    yearsActive: 20,
    accentHue: 180,
    achievements: [
      "Hosted The Daily Show 2015–2022",
      "Born a Crime: 100+ weeks on the NYT bestseller list",
      "Hosted the Grammy Awards three consecutive years",
    ],
    awards: [
      { name: "Erasmus Prize", year: 2023 },
      { name: "NAACP Image Award — Outstanding Talk Series", year: 2018, work: "The Daily Show" },
    ],
    works: [
      { title: "Off the Record Tour", year: 2023, kind: "event" },
      { title: "Born a Crime", year: 2016, kind: "book" },
      { title: "The Daily Show", year: 2015, kind: "show", meta: "Comedy Central" },
    ],
    socials: [
      { platform: "Instagram", handle: "@trevornoah", followers: 30_000_000 },
      { platform: "X", handle: "@Trevornoah", followers: 11_000_000 },
    ],
    faq: [
      { q: "What formats does Trevor offer?", a: "Stand-up sets, keynote conversations, moderated panels and award-show hosting." },
    ],
  },

  // ───────── Keynote Speakers ─────────
  {
    slug: "brene-brown",
    name: "Brené Brown",
    tagline: "The researcher who made vulnerability a leadership superpower",
    bio: "Dr. Brené Brown is a research professor at the University of Houston whose work on vulnerability, courage and shame has shaped modern leadership. Her TED talk is among the most viewed ever, and her six No. 1 New York Times bestsellers anchor keynotes that transform organizations.",
    gender: "female",
    category: "speakers",
    country: "US",
    manager: 5,
    featured: true,
    trendingScore: 71,
    popularity: 82,
    rating: 4.9,
    reviewCount: 89,
    followers: 9_000_000,
    feeFrom: 150_000,
    feeTo: 350_000,
    availability: "available",
    yearsActive: 20,
    accentHue: 55,
    achievements: [
      "TED talk with 60M+ views — among the top five of all time",
      "Six No. 1 New York Times bestsellers",
      "First researcher with a filmed Netflix special (The Call to Courage)",
    ],
    awards: [
      { name: "Texas Women's Hall of Fame", year: 2023 },
    ],
    works: [
      { title: "Atlas of the Heart", year: 2021, kind: "book" },
      { title: "Dare to Lead", year: 2018, kind: "book" },
      { title: "The Call to Courage", year: 2019, kind: "show", meta: "Netflix" },
    ],
    socials: [
      { platform: "Instagram", handle: "@brenebrown", followers: 5_000_000 },
      { platform: "LinkedIn", handle: "Brené Brown", followers: 4_000_000 },
    ],
    faq: [
      { q: "What is Brené's signature keynote?", a: "Dare to Lead — courage-building for leadership teams, adaptable from 45-minute keynote to half-day workshop." },
    ],
  },
  {
    slug: "simon-sinek",
    name: "Simon Sinek",
    tagline: "Start With Why — the most-watched business talk in TED history",
    bio: "Simon Sinek is an author and optimist whose concept of the Golden Circle — Start With Why — became one of the most influential ideas in modern business. His keynotes on purpose, trust and infinite-minded leadership are a fixture at the world's largest corporate gatherings.",
    gender: "male",
    category: "speakers",
    country: "GB",
    manager: 5,
    trendingScore: 68,
    popularity: 78,
    rating: 4.8,
    reviewCount: 76,
    followers: 15_000_000,
    feeFrom: 100_000,
    feeTo: 250_000,
    availability: "available",
    yearsActive: 16,
    accentHue: 250,
    achievements: [
      "Start With Why TED talk: 60M+ views",
      "Multiple NYT bestsellers including Leaders Eat Last",
      "Founder of The Optimism Company",
    ],
    awards: [
      { name: "Thinkers50 — Top Management Thinkers", year: 2021 },
    ],
    works: [
      { title: "The Infinite Game", year: 2019, kind: "book" },
      { title: "Leaders Eat Last", year: 2014, kind: "book" },
      { title: "Start With Why", year: 2009, kind: "book" },
    ],
    socials: [
      { platform: "Instagram", handle: "@simonsinek", followers: 8_000_000 },
      { platform: "LinkedIn", handle: "Simon Sinek", followers: 7_000_000 },
    ],
    faq: [
      { q: "Does Simon offer virtual keynotes?", a: "Yes — broadcast-quality virtual and hybrid formats with live Q&A." },
    ],
  },

  // ───────── Creators & Influencers ─────────
  {
    slug: "mrbeast",
    name: "MrBeast",
    tagline: "The most-subscribed individual creator on Earth",
    bio: "Jimmy Donaldson, known as MrBeast, built the largest individual YouTube channel in the world on the back of colossal challenge videos and radical philanthropy. His ventures — Feastables, Beast Philanthropy and Beast Games — extend a media empire watched by hundreds of millions.",
    gender: "male",
    category: "influencers",
    country: "US",
    manager: 6,
    featured: true,
    trendingScore: 96,
    popularity: 97,
    rating: 4.7,
    reviewCount: 44,
    followers: 620_000_000,
    feeFrom: 500_000,
    feeTo: 2_000_000,
    availability: "limited",
    yearsActive: 12,
    accentHue: 195,
    achievements: [
      "Most-subscribed individual YouTube channel (300M+)",
      "Beast Games: Amazon's biggest unscripted launch",
      "Team Trees & Team Seas raised $60M+ for the planet",
    ],
    awards: [
      { name: "Streamy Award — Creator of the Year", year: 2023 },
      { name: "Forbes Top Creator", year: 2024 },
    ],
    works: [
      { title: "Beast Games", year: 2024, kind: "show", meta: "Prime Video" },
      { title: "Feastables", year: 2022, kind: "event", meta: "CPG launch" },
      { title: "Team Seas", year: 2021, kind: "event", meta: "$30M ocean cleanup" },
    ],
    socials: [
      { platform: "YouTube", handle: "@MrBeast", followers: 340_000_000 },
      { platform: "Instagram", handle: "@mrbeast", followers: 60_000_000 },
      { platform: "X", handle: "@MrBeast", followers: 30_000_000 },
    ],
    faq: [
      { q: "What campaign formats does MrBeast offer?", a: "Integrated video features, product collaborations and appearance-driven activations — scoped case by case." },
    ],
  },
  {
    slug: "charli-damelio",
    name: "Charli D'Amelio",
    tagline: "TikTok's first 100-million-follower creator",
    bio: "Charli D'Amelio is a dancer and creator who became the first person to reach 100 million followers on TikTok. She has since expanded into television, Broadway and fashion — winning Dancing with the Stars and building one of Gen Z's most recognizable personal brands.",
    gender: "female",
    category: "influencers",
    country: "US",
    manager: 6,
    trendingScore: 82,
    popularity: 87,
    rating: 4.7,
    reviewCount: 29,
    followers: 210_000_000,
    feeFrom: 100_000,
    feeTo: 350_000,
    availability: "available",
    yearsActive: 7,
    accentHue: 340,
    achievements: [
      "First TikTok creator to 100M followers",
      "Dancing with the Stars champion (2022)",
      "Broadway debut in & Juliet (2024)",
    ],
    awards: [
      { name: "People's Choice — Social Star", year: 2021 },
    ],
    works: [
      { title: "& Juliet", year: 2024, kind: "event", meta: "Broadway" },
      { title: "Dancing with the Stars", year: 2022, kind: "show", meta: "Season 31 winner" },
      { title: "The D'Amelio Show", year: 2021, kind: "show", meta: "Hulu" },
    ],
    socials: [
      { platform: "TikTok", handle: "@charlidamelio", followers: 155_000_000 },
      { platform: "Instagram", handle: "@charlidamelio", followers: 42_000_000 },
    ],
    faq: [
      { q: "What brand categories does Charli work with?", a: "Beauty, fashion, beverage and lifestyle — with creative approval on all content." },
    ],
  },

  // ───────── TV Hosts ─────────
  {
    slug: "oprah-winfrey",
    name: "Oprah Winfrey",
    tagline: "The queen of daytime — and the most influential interviewer alive",
    bio: "Oprah Winfrey is a broadcaster, producer and philanthropist whose talk show defined daytime television for 25 years. The first Black woman billionaire, her interviews remain global cultural events and her book club can move a title to the top of every chart overnight.",
    gender: "female",
    category: "tv-hosts",
    country: "US",
    manager: 4,
    featured: true,
    trendingScore: 75,
    popularity: 94,
    rating: 5.0,
    reviewCount: 71,
    followers: 60_000_000,
    feeFrom: 750_000,
    feeTo: 2_000_000,
    availability: "limited",
    yearsActive: 40,
    accentHue: 70,
    achievements: [
      "The Oprah Winfrey Show: highest-rated talk show in TV history",
      "Presidential Medal of Freedom recipient",
      "First Black woman billionaire",
      "Founder of OWN and Oprah's Book Club",
    ],
    awards: [
      { name: "Cecil B. DeMille Award", year: 2018 },
      { name: "Jean Hersholt Humanitarian Award", year: 2011 },
    ],
    works: [
      { title: "The Oprah Winfrey Show", year: 1986, kind: "show", meta: "25 seasons" },
      { title: "The Color Purple", year: 2023, kind: "film", meta: "Producer" },
      { title: "Oprah's Book Club", year: 1996, kind: "event" },
    ],
    socials: [
      { platform: "Instagram", handle: "@oprah", followers: 23_000_000 },
      { platform: "X", handle: "@Oprah", followers: 41_000_000 },
    ],
    faq: [
      { q: "What engagements does Ms. Winfrey consider?", a: "Marquee interviews, commencements and philanthropic galas, reviewed personally by her office." },
    ],
  },
  {
    slug: "gordon-ramsay",
    name: "Gordon Ramsay",
    tagline: "17 Michelin stars of television gold",
    bio: "Gordon Ramsay is a British chef and broadcaster whose restaurants have earned 17 Michelin stars and whose shows — Hell's Kitchen, MasterChef, Kitchen Nightmares — made him the most famous chef on television. His live cooking demonstrations and appearances sell out worldwide.",
    gender: "male",
    category: "tv-hosts",
    country: "GB",
    manager: 4,
    trendingScore: 79,
    popularity: 88,
    rating: 4.8,
    reviewCount: 52,
    followers: 130_000_000,
    feeFrom: 200_000,
    feeTo: 600_000,
    availability: "available",
    yearsActive: 30,
    accentHue: 20,
    achievements: [
      "17 Michelin stars earned across his restaurant group",
      "Hell's Kitchen airs in 200+ territories",
      "Most-followed chef on TikTok",
    ],
    awards: [
      { name: "OBE for services to hospitality", year: 2006 },
      { name: "Emmy nomination — MasterChef Junior", year: 2015 },
    ],
    works: [
      { title: "Hell's Kitchen", year: 2005, kind: "show", meta: "FOX" },
      { title: "MasterChef", year: 2010, kind: "show", meta: "FOX" },
      { title: "Restaurant Gordon Ramsay", year: 1998, kind: "event", meta: "3 Michelin stars" },
    ],
    socials: [
      { platform: "TikTok", handle: "@gordonramsayofficial", followers: 40_000_000 },
      { platform: "Instagram", handle: "@gordongram", followers: 18_000_000 },
    ],
    faq: [
      { q: "Does Gordon do live cooking events?", a: "Yes — masterclasses, brand launches and private dinners with full culinary production." },
    ],
  },

  // ───────── Authors ─────────
  {
    slug: "malcolm-gladwell",
    name: "Malcolm Gladwell",
    tagline: "The storyteller who turned social science into bestsellers",
    bio: "Malcolm Gladwell is a Canadian journalist and author whose books — The Tipping Point, Outliers, Blink — have sold tens of millions of copies and changed how business thinks about success. His Revisionist History podcast and captivating keynotes make complex ideas feel inevitable.",
    gender: "male",
    category: "authors",
    country: "CA",
    manager: 5,
    trendingScore: 62,
    popularity: 75,
    rating: 4.8,
    reviewCount: 58,
    followers: 3_000_000,
    feeFrom: 100_000,
    feeTo: 250_000,
    availability: "available",
    yearsActive: 25,
    accentHue: 95,
    achievements: [
      "Five consecutive NYT bestsellers",
      "Named one of Time's 100 Most Influential People",
      "Co-founder of Pushkin Industries",
    ],
    awards: [
      { name: "American Sociological Association Award for Excellence", year: 2007 },
    ],
    works: [
      { title: "Revenge of the Tipping Point", year: 2024, kind: "book" },
      { title: "Outliers", year: 2008, kind: "book" },
      { title: "Revisionist History", year: 2016, kind: "show", meta: "Podcast" },
    ],
    socials: [
      { platform: "X", handle: "@Gladwell", followers: 700_000 },
      { platform: "Instagram", handle: "@malcolmgladwell", followers: 500_000 },
    ],
    faq: [
      { q: "What is a Gladwell keynote like?", a: "A 45–60 minute narrative talk tailored to your industry, followed by moderated Q&A." },
    ],
  },
  {
    slug: "chimamanda-ngozi-adichie",
    name: "Chimamanda Ngozi Adichie",
    tagline: "One of the most vital literary voices of the century",
    bio: "Chimamanda Ngozi Adichie is a Nigerian novelist and essayist whose books Half of a Yellow Sun and Americanah earned global acclaim, and whose TEDx talk We Should All Be Feminists became a cultural touchstone sampled by Beyoncé and printed on Dior runways.",
    gender: "female",
    category: "authors",
    country: "NG",
    manager: 5,
    trendingScore: 60,
    popularity: 72,
    rating: 4.9,
    reviewCount: 33,
    followers: 2_000_000,
    feeFrom: 75_000,
    feeTo: 200_000,
    availability: "available",
    yearsActive: 22,
    accentHue: 275,
    achievements: [
      "MacArthur 'Genius' Fellowship",
      "We Should All Be Feminists: 10M+ TEDx views",
      "Women's Prize for Fiction 'Winner of Winners' (2020)",
    ],
    awards: [
      { name: "Women's Prize for Fiction", year: 2007, work: "Half of a Yellow Sun" },
      { name: "MacArthur Fellowship", year: 2008 },
    ],
    works: [
      { title: "Dream Count", year: 2025, kind: "book" },
      { title: "Americanah", year: 2013, kind: "book" },
      { title: "Half of a Yellow Sun", year: 2006, kind: "book" },
    ],
    socials: [
      { platform: "Instagram", handle: "@chimamanda_adichie", followers: 1_500_000 },
    ],
    faq: [
      { q: "Does Chimamanda speak at universities?", a: "Yes — literary festivals, commencements and conversations on literature and feminism." },
    ],
  },

  // ───────── Public Figures ─────────
  {
    slug: "barack-obama",
    name: "Barack Obama",
    tagline: "44th President of the United States",
    bio: "Barack Obama served as the 44th President of the United States from 2009 to 2017. A Nobel Peace Prize laureate and author of the record-breaking memoir A Promised Land, he remains one of the most in-demand speakers in the world, with Higher Ground producing Oscar-winning films.",
    gender: "male",
    category: "public-figures",
    country: "US",
    manager: 5,
    featured: true,
    trendingScore: 77,
    popularity: 96,
    rating: 5.0,
    reviewCount: 62,
    followers: 250_000_000,
    feeFrom: 400_000,
    feeTo: 1_000_000,
    availability: "limited",
    yearsActive: 28,
    accentHue: 220,
    achievements: [
      "44th President of the United States (2009–2017)",
      "Nobel Peace Prize laureate (2009)",
      "A Promised Land sold 887,000 copies on day one",
      "Two Grammy Awards for audiobook narration",
    ],
    awards: [
      { name: "Nobel Peace Prize", year: 2009 },
      { name: "Grammy — Best Spoken Word Album", year: 2008, work: "The Audacity of Hope" },
      { name: "Emmy — Outstanding Narrator", year: 2022, work: "Our Great National Parks" },
    ],
    works: [
      { title: "A Promised Land", year: 2020, kind: "book" },
      { title: "Our Great National Parks", year: 2022, kind: "show", meta: "Netflix, narrator" },
      { title: "American Symphony", year: 2023, kind: "film", meta: "Producer" },
    ],
    socials: [
      { platform: "X", handle: "@BarackObama", followers: 130_000_000 },
      { platform: "Instagram", handle: "@barackobama", followers: 38_000_000 },
    ],
    faq: [
      { q: "What engagements does President Obama accept?", a: "Keynotes for global summits, leadership forums and select philanthropic events, coordinated through his office." },
    ],
  },
  {
    slug: "michelle-obama",
    name: "Michelle Obama",
    tagline: "Former First Lady and author of the decade's best-selling memoir",
    bio: "Michelle Obama is a lawyer, author and former First Lady of the United States whose memoir Becoming sold over 17 million copies — among the best-selling memoirs in history. Her initiatives on education, health and voting rights continue through the Obama Foundation.",
    gender: "female",
    category: "public-figures",
    country: "US",
    manager: 5,
    trendingScore: 73,
    popularity: 90,
    rating: 5.0,
    reviewCount: 48,
    followers: 90_000_000,
    feeFrom: 350_000,
    feeTo: 800_000,
    availability: "limited",
    yearsActive: 18,
    accentHue: 300,
    achievements: [
      "Becoming: 17M+ copies sold worldwide",
      "Grammy winner for the Becoming audiobook",
      "Founded Let's Move! and When We All Vote",
    ],
    awards: [
      { name: "Grammy — Best Spoken Word Album", year: 2020, work: "Becoming" },
      { name: "NAACP Image Award — Outstanding Literary Work", year: 2019, work: "Becoming" },
    ],
    works: [
      { title: "The Light We Carry", year: 2022, kind: "book" },
      { title: "Becoming", year: 2018, kind: "book" },
      { title: "Waffles + Mochi", year: 2021, kind: "show", meta: "Netflix" },
    ],
    socials: [
      { platform: "Instagram", handle: "@michelleobama", followers: 57_000_000 },
      { platform: "X", handle: "@MichelleObama", followers: 22_000_000 },
    ],
    faq: [
      { q: "What themes does Mrs. Obama speak on?", a: "Leadership, education, community and resilience — in keynote or moderated-conversation formats." },
    ],
  },

  // ───────── Fashion ─────────
  {
    slug: "naomi-campbell",
    name: "Naomi Campbell",
    tagline: "The original supermodel — four decades on fashion's front line",
    bio: "Naomi Campbell is a British supermodel whose four-decade career broke barriers across every major runway, campaign and cover in fashion. The first Black model on the cover of French Vogue, she remains an icon of the industry and a dedicated philanthropist through Fashion for Relief.",
    gender: "female",
    category: "fashion",
    country: "GB",
    manager: 1,
    trendingScore: 66,
    popularity: 81,
    rating: 4.7,
    reviewCount: 27,
    followers: 17_000_000,
    feeFrom: 150_000,
    feeTo: 500_000,
    availability: "available",
    yearsActive: 39,
    accentHue: 10,
    achievements: [
      "First Black model on the cover of French Vogue (1988)",
      "Walked for every major fashion house across four decades",
      "Founder of Fashion for Relief charity",
      "Subject of a V&A retrospective exhibition (2024)",
    ],
    awards: [
      { name: "CFDA Fashion Icon Award", year: 2018 },
      { name: "British Fashion Council Special Recognition", year: 2019 },
    ],
    works: [
      { title: "NAOMI: In Fashion (V&A)", year: 2024, kind: "event", meta: "Retrospective" },
      { title: "The Supermodels", year: 2023, kind: "show", meta: "Apple TV+" },
      { title: "Fashion for Relief", year: 2005, kind: "event", meta: "Charity gala series" },
    ],
    socials: [
      { platform: "Instagram", handle: "@naomi", followers: 16_000_000 },
    ],
    faq: [
      { q: "Is Naomi available for runway and campaigns?", a: "Yes — runway, campaigns, front-row appearances and gala hosting worldwide." },
    ],
  },
];

// Fictional client testimonials shown on the homepage (demo content)
export const TESTIMONIALS = [
  {
    quote:
      "Aurum delivered the impossible: a headline performance confirmed in nine days, contracts and logistics handled to the letter. Our gala raised three times its target.",
    name: "Elena Vasquez",
    role: "Director of Events, Meridian Foundation",
  },
  {
    quote:
      "The escrow structure gave our board total confidence. Funds released on milestones, every deliverable documented. This is how talent booking should work.",
    name: "Thomas Wright",
    role: "CMO, Halcyon Motors",
  },
  {
    quote:
      "From shortlist to signed contract in under two weeks — for a name we assumed was unreachable. The concierge team is extraordinary.",
    name: "Priya Sharma",
    role: "Founder, Solstice Weddings",
  },
  {
    quote:
      "We've booked keynote speakers through Aurum for three consecutive summits. The calibre of talent and the polish of the process keep us coming back.",
    name: "Daniel Osei",
    role: "Head of Programming, Vertex Summit",
  },
];

// Fictional partner logos for the trust marquee (invented brands)
export const PARTNER_BRANDS = [
  "Halcyon Motors",
  "Maison Verre",
  "Vertex Summit",
  "Solstice",
  "Atlas & Co.",
  "Meridian Foundation",
  "Aurora Air",
  "Belmont Hotels",
  "Ovation Media",
  "Lyra Beauty",
  "Northbridge Capital",
  "Velvet House",
];
